### ISSUE TITLE
App introduction plays after each startup

### ISSUE THREAD

**Issue by YellingTree** [PhieF/CarnetAndroid#81]
If app is cleared from the recents page then it will play through the introduction as if it's been freshly installed.
Android Version: 10
Installed from F-Droid

**Comment by bgrayburn** [comment]
Also seeing this behavior although it happens every app start for me. I'm using KISS launcher so maybe that somehow equates to no recent app list?

**Comment by toxpal** [comment]
I have exactly the same issue on 2 different phones (Android 9). The issue is not related to Launcher, it's a bug in the app itself. I experience bug this way on both devices:

Every time I open app (after closing it from recent apps list), it displays introduction and suggests me to setup app.
No matter what I do, it then resets settings (some users reported that app deletes all settings and notes for them - https://github.com/PhieF/CarnetAndroid/issues/80).
I can continue using app then (my notes are here), but only if I don't close the app. Once I do, everything starts over.

**Comment by Wrexthor** [comment]
have the same issue

**Comment by Kilroy1126** [comment]
Same, every app start (reboot or cleared from recent) I see initial setup.

(Couple bugs but I really like it so far 🙂)

**Comment by radl97** [comment]
It seems fixed in 0.19.3 (see commit https://github.com/PhieF/CarnetAndroid/commit/e3a42589155c04ca883d293725ca7af6ebce637a ).
Can you push the changes to F-Droid please?

**Comment by toxpal** [comment]
Fix is released as a new version on Fdroid. Works great.

**Comment by PhieF** [comment]
Thanks <3
